language: python
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
- '3.8'
install:
- 'pip install -r dev-requirements.txt'
script:
- pytest --vcr-record=none --cov=tenable tests
deploy:
  provider: pypi
  user: stevemcgrath
  password:
    secure: oqakiyseiKO3b2xoOLxCPDNJI/kPrrjk06OQG7GzbbjI1D8lMgQB6TnIW1qEv2MdXlDuQd4ViqAV5UQyt1mnibjEpdI2ECAtGi+CJSrmmQxiEuiNGJE35p+7slc5GKoBOkV7CEu2o4fKvAQXCWtIgN0DDF0IFpeCol2FtKVo9V2Iw8jl//WL9IEis+56SxccUXf2bHMkwOuYh/pHv27JdMvox7/hhiG3FmHgGA1GunAlbiUrOhz6+wTXJNFlIBjDHnwstTP1MmdmCJNlsftzE3hD0CA8BS1FtiJY0UlSbMfZv8wwwDAnaZqmO1la8za/0aYIKaTUkvTW9rxckv+aZi2/Up73osdQ4Lw2EydRaUweYPAPqHthsa1rDFAvteGBm8y3JfJoFWaO4Z+dxc02+LMv+oxZwXd3QFZMniEBV/YOYB6tCUifKjD/n+RT/CVLVEjaGBT3kUIF6G1rI8O9HgiCiTLWifQ1xLRy1KNxtdJvDO6GmmAs4XhbZy1vrerygp0OXBT65b1HV/9GJwvyTNeuhztdXARslJGS7tA6KCFG0NoiU+G82nJ8mzm+5yBE3uf+gBW+413dLMoD+vSeCjPM7cUZ2cGdkktFT/Vse0LHg0tM6aqIeODm47toS1Cbix81G4L/SHbHiKJ5zCsO3GgLPlO2YdU9dx92PFRnMSY=
  skip_existing: true
  on:
    tags: true
